version: "3.7"
services:
  app1:
    build: .
    hostname: "hi_krillin.host"
    environment:
      - RELEASE_NODE=app@hi_krillin.host
      - RELEASE_DISTRIBUTION=name
      - RELEASE_COOKIE=mycookie
    ports:
      - "127.0.0.1:4001:4000"
  app2:
    build: .
    hostname: "hi_vegeta.host"
    environment:
      - RELEASE_NODE=app@hi_vegeta.host
      - RELEASE_DISTRIBUTION=name
      - RELEASE_COOKIE=mycookie
    ports:
      - "127.0.0.1:4002:4000"